// ═══════════════════════════════════════
//  KGS Informatique — Mock Data
// ═══════════════════════════════════════

export const ARTICLES = [
  {
    id: 1, slug: 'git-workflow-avance',
    title: 'Git Workflow Avancé : Branching, Rebasing et Pull Requests',
    excerpt: 'Maîtrisez les workflows Git professionnels utilisés dans les grandes équipes de développement. Du gitflow à trunk-based development.',
    cover: null, coverColor: '#dbeafe',
    category: 'DevOps', tags: ['git','workflow','devops'],
    author: { name: 'Kouam G. Stive', initials: 'KS', role: 'Fondateur KGS' },
    readTime: '8 min', date: '12 mars 2026', views: 1247, likes: 89, featured: true,
  },
  {
    id: 2, slug: 'vue3-composition-api',
    title: 'Vue 3 Composition API : Guide Complet pour Débutants',
    excerpt: 'Tout ce que vous devez savoir sur la Composition API de Vue 3 : ref, reactive, computed, watch et les composables personnalisés.',
    cover: null, coverColor: '#dcfce7',
    category: 'Vue.js', tags: ['vue','javascript','frontend'],
    author: { name: 'Marie Nguele', initials: 'MN', role: 'Formatrice Senior' },
    readTime: '12 min', date: '8 mars 2026', views: 892, likes: 67, featured: true,
  },
  {
    id: 3, slug: 'python-data-science-intro',
    title: 'Python pour la Data Science : Par où commencer en 2026 ?',
    excerpt: 'NumPy, Pandas, Matplotlib — découvrez l\'écosystème Python pour l\'analyse de données avec des exemples concrets et africains.',
    cover: null, coverColor: '#fef9c3',
    category: 'Python', tags: ['python','data-science','ml'],
    author: { name: 'Jean-Paul Biya', initials: 'JB', role: 'Data Engineer' },
    readTime: '10 min', date: '5 mars 2026', views: 654, likes: 45, featured: false,
  },
  {
    id: 4, slug: 'api-rest-nodejs-express',
    title: 'Construire une API REST solide avec Node.js & Express',
    excerpt: 'Architecture, authentification JWT, validation des données et bonnes pratiques pour des APIs robustes et maintenables.',
    cover: null, coverColor: '#ede9fe',
    category: 'Backend', tags: ['nodejs','express','api','rest'],
    author: { name: 'Kouam G. Stive', initials: 'KS', role: 'Fondateur KGS' },
    readTime: '15 min', date: '1 mars 2026', views: 1102, likes: 78, featured: false,
  },
  {
    id: 5, slug: 'docker-introduction-cameroun',
    title: 'Docker pour les développeurs camerounais : Guide pratique',
    excerpt: 'Containerisation de vos applications localement et en production. Stop aux "ça marche sur ma machine" !',
    cover: null, coverColor: '#ffedd5',
    category: 'DevOps', tags: ['docker','devops','containers'],
    author: { name: 'Marie Nguele', initials: 'MN', role: 'Formatrice Senior' },
    readTime: '9 min', date: '25 fév 2026', views: 445, likes: 32, featured: false,
  },
  {
    id: 6, slug: 'freelance-developpeur-afrique',
    title: 'Devenir freelance développeur en Afrique : Guide complet 2026',
    excerpt: 'Plateformes, tarifs, clients, paiements internationaux — tout ce que vous devez savoir pour lancer votre activité freelance.',
    cover: null, coverColor: '#dcfce7',
    category: 'Carrière', tags: ['freelance','carriere','business'],
    author: { name: 'Kouam G. Stive', initials: 'KS', role: 'Fondateur KGS' },
    readTime: '18 min', date: '20 fév 2026', views: 2341, likes: 187, featured: true,
  },
]

export const FORMATIONS = [
  {
    id: 1, slug: 'fullstack-vue-node',
    title: 'Développement Fullstack Vue.js + Node.js',
    subtitle: 'De zéro à développeur fullstack opérationnel',
    cover: null, coverColor: '#dbeafe',
    category: 'Web', level: 'Intermédiaire',
    instructor: { name: 'Kouam G. Stive', initials: 'KS', bio: 'Fondateur KGS Informatique, 8 ans d\'expérience' },
    price: '45 000 FCFA', priceNum: 45000, isFree: false,
    duration: '40h de contenu', lessons: 68, students: 234,
    rating: 4.8, reviews: 89,
    tags: ['vue','nodejs','fullstack','javascript'],
    description: 'Formation complète pour maîtriser le développement web fullstack avec Vue.js 3 et Node.js. Vous construirez 3 projets réels.',
    modules: [
      { title: 'Fondamentaux JavaScript ES6+', lessons: 12, duration: '6h' },
      { title: 'Vue.js 3 et Composition API', lessons: 18, duration: '12h' },
      { title: 'Node.js et Express', lessons: 14, duration: '9h' },
      { title: 'Base de données MongoDB', lessons: 10, duration: '7h' },
      { title: 'Projet Final : Plateforme E-learning', lessons: 14, duration: '6h' },
    ],
    featured: true, badge: 'Bestseller',
  },
  {
    id: 2, slug: 'python-data-science',
    title: 'Python & Data Science Appliquée',
    subtitle: 'Analyse de données et Machine Learning avec Python',
    cover: null, coverColor: '#fef9c3',
    category: 'Data', level: 'Débutant',
    instructor: { name: 'Jean-Paul Biya', initials: 'JB', bio: 'Data Engineer chez une fintech africaine' },
    price: '35 000 FCFA', priceNum: 35000, isFree: false,
    duration: '30h de contenu', lessons: 52, students: 167,
    rating: 4.6, reviews: 54,
    tags: ['python','data','machine-learning'],
    description: 'Apprenez Python depuis zéro et plongez dans l\'analyse de données avec NumPy, Pandas, Matplotlib et scikit-learn.',
    modules: [
      { title: 'Python de zéro', lessons: 10, duration: '5h' },
      { title: 'NumPy et Pandas', lessons: 14, duration: '9h' },
      { title: 'Visualisation avec Matplotlib', lessons: 10, duration: '6h' },
      { title: 'Machine Learning avec scikit-learn', lessons: 18, duration: '10h' },
    ],
    featured: true, badge: 'Nouveau',
  },
  {
    id: 3, slug: 'devops-docker-ci-cd',
    title: 'DevOps : Docker, CI/CD & Déploiement',
    subtitle: 'Automatisez vos déploiements comme un pro',
    cover: null, coverColor: '#ede9fe',
    category: 'DevOps', level: 'Avancé',
    instructor: { name: 'Marie Nguele', initials: 'MN', bio: 'DevOps Engineer, certifiée AWS' },
    price: 'Gratuit', priceNum: 0, isFree: true,
    duration: '20h de contenu', lessons: 35, students: 891,
    rating: 4.9, reviews: 234,
    tags: ['docker','devops','ci-cd','github-actions'],
    description: 'Maîtrisez la containerisation avec Docker, mettez en place des pipelines CI/CD avec GitHub Actions et déployez sur le cloud.',
    modules: [
      { title: 'Docker et containerisation', lessons: 12, duration: '8h' },
      { title: 'Docker Compose', lessons: 8, duration: '4h' },
      { title: 'GitHub Actions CI/CD', lessons: 10, duration: '5h' },
      { title: 'Déploiement AWS/VPS', lessons: 5, duration: '3h' },
    ],
    featured: true, badge: 'Gratuit',
  },
  {
    id: 4, slug: 'mobile-flutter',
    title: 'Développement Mobile avec Flutter',
    subtitle: 'Créez des apps iOS et Android avec une seule codebase',
    cover: null, coverColor: '#dcfce7',
    category: 'Mobile', level: 'Intermédiaire',
    instructor: { name: 'Kouam G. Stive', initials: 'KS', bio: 'Fondateur KGS Informatique' },
    price: '50 000 FCFA', priceNum: 50000, isFree: false,
    duration: '45h de contenu', lessons: 78, students: 143,
    rating: 4.7, reviews: 41,
    tags: ['flutter','dart','mobile','ios','android'],
    description: 'Apprenez Flutter et Dart pour créer des applications mobiles professionnelles disponibles sur iOS et Android.',
    modules: [
      { title: 'Dart Language Fundamentals', lessons: 14, duration: '8h' },
      { title: 'Flutter Widgets & Layouts', lessons: 20, duration: '12h' },
      { title: 'State Management avec Riverpod', lessons: 16, duration: '10h' },
      { title: 'Firebase & Backend', lessons: 14, duration: '9h' },
      { title: 'Publication App Stores', lessons: 14, duration: '6h' },
    ],
    featured: false, badge: null,
  },
]

export const PROJETS = [
  {
    id: 1, slug: 'kgs-learn',
    title: 'KGS Learn — Plateforme E-Learning',
    description: 'Une plateforme d\'apprentissage en ligne moderne avec cours vidéo, quiz interactifs et suivi de progression.',
    cover: null, coverColor: '#dbeafe',
    tags: ['Vue.js', 'Node.js', 'MongoDB', 'Tailwind'],
    category: 'Web App',
    status: 'En production',
    github: 'https://github.com/kgs-info/kgs-learn',
    demo: 'https://learn.kgs-info.cm',
    stars: 127, forks: 34,
    team: [{ initials:'KS' },{ initials:'MN' }],
    featured: true,
  },
  {
    id: 2, slug: 'cameroon-jobs',
    title: 'CamJobs — Offres d\'emploi Tech',
    description: 'Plateforme de mise en relation entre entreprises et développeurs camerounais. Filtres par stack, ville et niveau.',
    cover: null, coverColor: '#dcfce7',
    tags: ['Vue.js', 'Firebase', 'Algolia'],
    category: 'SaaS',
    status: 'En développement',
    github: 'https://github.com/kgs-info/camjobs',
    demo: null,
    stars: 89, forks: 12,
    team: [{ initials:'KS' },{ initials:'JB' }],
    featured: true,
  },
  {
    id: 3, slug: 'api-mobile-money',
    title: 'MoMo API — SDK Mobile Money',
    description: 'SDK JavaScript/Node.js pour intégrer facilement Orange Money et MTN MoMo dans vos applications.',
    cover: null, coverColor: '#ffedd5',
    tags: ['Node.js', 'TypeScript', 'NPM Package'],
    category: 'Open Source',
    status: 'En production',
    github: 'https://github.com/kgs-info/momo-api',
    demo: 'https://npm.im/kgs-momo',
    stars: 342, forks: 67,
    team: [{ initials:'KS' }],
    featured: true,
  },
]

export const FORUM_POSTS = [
  { id:1, title:'Comment déployer un projet Vue.js sur un VPS en Afrique ?', author:{ name:'dev_alpha237', initials:'DA' }, category:'DevOps', replies:12, views:234, solved:true, date:'il y a 2h' },
  { id:2, title:'Paiement Mobile Money avec Orange API — Sandbox qui ne fonctionne plus', author:{ name:'momo_integration', initials:'MI' }, category:'API', replies:7, views:189, solved:false, date:'il y a 5h' },
  { id:3, title:'Quelle stack recommandez-vous pour une startup camerounaise en 2026 ?', author:{ name:'startup_camer', initials:'SC' }, category:'Discussion', replies:28, views:892, solved:false, date:'hier' },
  { id:4, title:'Erreur CORS avec mon API Node.js derrière Nginx', author:{ name:'backend_nde', initials:'BN' }, category:'Backend', replies:5, views:145, solved:true, date:'hier' },
  { id:5, title:'Formation Flutter vs React Native : laquelle choisir ?', author:{ name:'mobile_coder', initials:'MC' }, category:'Mobile', replies:19, views:567, solved:false, date:'il y a 2 jours' },
  { id:6, title:'Comment obtenir un stage dans une entreprise tech à Douala ?', author:{ name:'junior_dev_cm', initials:'JD' }, category:'Carrière', replies:34, views:1234, solved:false, date:'il y a 3 jours' },
]

export const ASTUCES = [
  { id:1, title:'10 raccourcis VS Code que tout dev devrait connaître', emoji:'⚡', date:'14 mars 2026' },
  { id:2, title:'Productivité : Comment gérer son temps en tant que développeur freelance', emoji:'🕐', date:'10 mars 2026' },
  { id:3, title:'Les meilleures extensions Chrome pour développeurs en 2026', emoji:'🔧', date:'7 mars 2026' },
  { id:4, title:'Comment bien rédiger un README professionnel sur GitHub', emoji:'📄', date:'3 mars 2026' },
]

export const STATS = [
  { val: '2K+',  label: 'Membres actifs' },
  { val: '150+', label: 'Articles publiés' },
  { val: '12',   label: 'Formations disponibles' },
  { val: '89%',  label: 'Taux de satisfaction' },
]
